//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCount.Cli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCount.Cli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can file a Bug Report at https://github.com/alastairlundy/WCount.
        /// </summary>
        internal static string Exceptions_BugReport_FileIssue {
            get {
                return ResourceManager.GetString("Exceptions.BugReport.FileIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If this was unintended or unexpected, it would really help if you file a Bug Report..
        /// </summary>
        internal static string Exceptions_BugReport_Request {
            get {
                return ResourceManager.GetString("Exceptions.BugReport.Request", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The program was unable to find the specified file. If the file exists, consider checking your input for typos or mistakes..
        /// </summary>
        internal static string Exceptions_FileNotFound {
            get {
                return ResourceManager.GetString("Exceptions.FileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No file was provided as an argument to be used..
        /// </summary>
        internal static string Exceptions_NoFileProvided {
            get {
                return ResourceManager.GetString("Exceptions.NoFileProvided", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of bytes in one or more specified files..
        /// </summary>
        internal static string WCount_App_Bytes_Description {
            get {
                return ResourceManager.GetString("WCount.App.Bytes.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of characters in one or more specified files..
        /// </summary>
        internal static string WCount_App_Chars_Description {
            get {
                return ResourceManager.GetString("WCount.App.Chars.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of lines, words, characters, and/or bytes in one or more specified files..
        /// </summary>
        internal static string WCount_App_Description {
            get {
                return ResourceManager.GetString("WCount.App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bytes.
        /// </summary>
        internal static string WCount_App_Labels_Bytes_Plural {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Bytes.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte.
        /// </summary>
        internal static string WCount_App_Labels_Bytes_Singular {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Bytes.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Characters.
        /// </summary>
        internal static string WCount_App_Labels_Characters_Plural {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Characters.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Character.
        /// </summary>
        internal static string WCount_App_Labels_Characters_Singular {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Characters.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lines.
        /// </summary>
        internal static string WCount_App_Labels_Lines_Plural {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Lines.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string WCount_App_Labels_Lines_Singular {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Lines.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string WCount_App_Labels_Total {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Total", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string WCount_App_Labels_Words_Plural {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Words.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string WCount_App_Labels_Words_Singular {
            get {
                return ResourceManager.GetString("WCount.App.Labels.Words.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of lines in one or more specified files..
        /// </summary>
        internal static string WCount_App_Lines_Description {
            get {
                return ResourceManager.GetString("WCount.App.Lines.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WCount.
        /// </summary>
        internal static string WCount_App_Name {
            get {
                return ResourceManager.GetString("WCount.App.Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of words in one or more specified files..
        /// </summary>
        internal static string WCount_App_Words_Description {
            get {
                return ResourceManager.GetString("WCount.App.Words.Description", resourceCulture);
            }
        }
    }
}
