//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCountUI.Wasm.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCountUI.Wasm.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pasting clipboard failed. Here&apos;s the exception in case you need it:.
        /// </summary>
        internal static string Editor_PasteClipboard_Exception {
            get {
                return ResourceManager.GetString("Editor_PasteClipboard_Exception", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear.
        /// </summary>
        internal static string Labels_Buttons_Clear {
            get {
                return ResourceManager.GetString("Labels.Buttons.Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chars.
        /// </summary>
        internal static string Labels_Chars_Plural {
            get {
                return ResourceManager.GetString("Labels.Chars.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Char.
        /// </summary>
        internal static string Labels_Chars_Singular {
            get {
                return ResourceManager.GetString("Labels.Chars.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Words.
        /// </summary>
        internal static string Labels_Words_Plural {
            get {
                return ResourceManager.GetString("Labels.Words.Plural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Word.
        /// </summary>
        internal static string Labels_Words_Singular {
            get {
                return ResourceManager.GetString("Labels.Words.Singular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your text goes here..
        /// </summary>
        internal static string Placeholders_TextArea {
            get {
                return ResourceManager.GetString("Placeholders.TextArea", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About WCount.
        /// </summary>
        internal static string Titles_About_WCount {
            get {
                return ResourceManager.GetString("Titles.About.WCount", resourceCulture);
            }
        }
    }
}
