//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WCountCli.Localizations {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WCountCli.Localizations.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A cross-platform word counting program and wc alternative..
        /// </summary>
        internal static string App_Description {
            get {
                return ResourceManager.GetString("App.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of bytes in a file or string..
        /// </summary>
        internal static string Arguments_ByteCount_Description {
            get {
                return ResourceManager.GetString("Arguments.ByteCount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of characters in a file or string..
        /// </summary>
        internal static string Arguments_CharacterCount_Description {
            get {
                return ResourceManager.GetString("Arguments.CharacterCount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The file path(s) of the file to be read..
        /// </summary>
        internal static string Arguments_FilePaths_Description {
            get {
                return ResourceManager.GetString("Arguments.FilePaths.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of lines in a file or string..
        /// </summary>
        internal static string Arguments_LineCount_Description {
            get {
                return ResourceManager.GetString("Arguments.LineCount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Count the number of words in a file or string..
        /// </summary>
        internal static string Arguments_WordCount_Description {
            get {
                return ResourceManager.GetString("Arguments.WordCount.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prints the version of WCount CLI to the console..
        /// </summary>
        internal static string Commands_Version_Description {
            get {
                return ResourceManager.GetString("Commands.Version.Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total.
        /// </summary>
        internal static string Output_Labels_Total {
            get {
                return ResourceManager.GetString("Output.Labels.Total", resourceCulture);
            }
        }
    }
}
